$LOAD_PATH << "."
require "lib/calendar"
require "lib/schedule"
require "lib/dbengine"
require "lib/loader"
require "lib/interface"
require "lib/utilityclass"
require "lib/spreadsheetmock"
require "lib/employee"
